### ISSUE TITLE
Why not use leadjs

### ISSUE THREAD

**Issue by femot** [visualjerk/vunction#1]
Just wondering why the author of leadjs is using an experimental framework like vue?

**Comment by visualjerk** [comment]
While evaluating the usage of leadjs for this project, very bad things started to happen. I chickened out and opted for the (admittingly risky) choice of using vue.

**Comment by femot** [comment]
Thanks for the swift response. I guess it all depends on the use case. I'm just surprised that you actually found a use case where leadjs does not fit. 🤷‍♂
